# Generated by Django 3.2.8 on 2021-11-02 10:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Calltrack_lite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_rec', models.CharField(max_length=14, verbose_name='ID из астериск')),
                ('text', models.TextField(default='', verbose_name='фраза клиента')),
                ('text_lemm', models.TextField(default='', verbose_name='нормализированная фраза')),
                ('date_time_calling', models.DateTimeField(default=datetime.datetime(2021, 11, 2, 15, 37, 51, 699068), verbose_name='время звонка')),
                ('innumber', models.CharField(max_length=11, verbose_name='номер тел.')),
                ('region', models.IntegerField(verbose_name='код региона')),
                ('dial_route', models.IntegerField(verbose_name='доб. номер')),
                ('key_words', models.CharField(max_length=150, verbose_name='кл. слова')),
                ('result_recognition', models.CharField(max_length=50, verbose_name='распознование')),
            ],
            options={
                'verbose_name': 'Звонок',
                'verbose_name_plural': 'Звонки',
            },
        ),
        migrations.CreateModel(
            name='Category_2_name_category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.IntegerField(verbose_name='номер категории')),
                ('name_category', models.CharField(max_length=20, verbose_name='название категории')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Category_managers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=50, verbose_name='ключ. слово')),
                ('name_man', models.CharField(max_length=100, verbose_name='имя менеджера')),
                ('phone_number', models.CharField(max_length=12, verbose_name='доб. номер')),
            ],
            options={
                'verbose_name': 'Менеджер',
                'verbose_name_plural': 'Менеджеры',
            },
        ),
        migrations.CreateModel(
            name='Code_filial_2_name_filial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_filial', models.IntegerField(verbose_name='код города филиала')),
                ('filial', models.CharField(max_length=50, verbose_name='название филиала')),
            ],
            options={
                'verbose_name': 'Филиал',
                'verbose_name_plural': 'Филиалы',
            },
        ),
        migrations.CreateModel(
            name='Depart_filial_2_phone_number',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('depart', models.CharField(max_length=50, verbose_name='отдел')),
                ('filial', models.CharField(max_length=50, verbose_name='филиал')),
                ('phone_number', models.IntegerField(verbose_name='доб. номер')),
                ('info', models.CharField(max_length=50, verbose_name='инфо')),
            ],
            options={
                'verbose_name': 'Доб.номер отдела',
                'verbose_name_plural': 'Доб.номера отделов',
            },
        ),
        migrations.CreateModel(
            name='Departs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('depart_name', models.CharField(max_length=150, verbose_name='название отдела')),
                ('depart_added_phone_number', models.CharField(max_length=11, verbose_name='номер тел.')),
            ],
            options={
                'verbose_name': 'Отдел',
                'verbose_name_plural': 'Отделы',
            },
        ),
        migrations.CreateModel(
            name='Regions_name_and_code',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_region', models.IntegerField(verbose_name='код региона')),
                ('name_region', models.CharField(max_length=100, verbose_name='название региона')),
            ],
            options={
                'verbose_name': 'Регион',
                'verbose_name_plural': 'Регионы',
            },
        ),
        migrations.CreateModel(
            name='Relate_code_region_and_filial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_region', models.IntegerField(verbose_name='код региона')),
                ('code_filial', models.IntegerField(verbose_name='код филиала')),
            ],
            options={
                'verbose_name': 'Регион филиала',
                'verbose_name_plural': 'Регионы филиалов',
            },
        ),
        migrations.CreateModel(
            name='Repeat_hallo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_repeat', models.FloatField(verbose_name='время в секундах после фразы клиента')),
                ('times_repeat', models.IntegerField(verbose_name='количестово повторов')),
                ('phrase_repeat', models.CharField(max_length=50, verbose_name='фраза для повтора')),
            ],
            options={
                'verbose_name': 'Фраза: я вас слушаю',
                'verbose_name_plural': 'Фразы: я вас слушаю',
            },
        ),
        migrations.CreateModel(
            name='Three_categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=50, verbose_name='ключ. слово')),
                ('category', models.IntegerField(verbose_name='номер категории')),
            ],
            options={
                'verbose_name': 'Ключевое слово',
                'verbose_name_plural': 'Ключевые слова',
            },
        ),
        migrations.CreateModel(
            name='Worktime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filial', models.CharField(max_length=50, verbose_name='филиал')),
                ('time_open', models.TimeField(verbose_name='Начало рабочего дня')),
                ('time_close', models.TimeField(verbose_name='Конец рабочего дня')),
            ],
            options={
                'verbose_name': 'Время работы',
                'verbose_name_plural': 'Время работы',
            },
        ),
    ]
