# Generated by Django 3.2.8 on 2021-10-11 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category_managers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=50, verbose_name='key word')),
                ('name_man', models.CharField(max_length=100, verbose_name='name of manager')),
                ('phone_number', models.CharField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='Code_filial_2_name_filial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_filial', models.IntegerField(verbose_name='city code of filial')),
                ('name', models.CharField(max_length=100, verbose_name='name of city filial')),
            ],
        ),
        migrations.CreateModel(
            name='Depart_filial_2_phone_number',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('depart', models.CharField(max_length=50, verbose_name='name of depart (or category)')),
                ('filial', models.CharField(max_length=50, verbose_name='name of city filial')),
                ('phone_number', models.IntegerField(verbose_name='phone number')),
                ('info', models.CharField(max_length=50, verbose_name='info about depart')),
            ],
        ),
        migrations.CreateModel(
            name='Three_categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=50, verbose_name='key word')),
                ('category', models.CharField(max_length=50, verbose_name='category of word (or depart)')),
            ],
        ),
    ]
