# Generated by Django 3.2.8 on 2021-10-11 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_back_end', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Worktime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filial', models.CharField(max_length=50, verbose_name='name of city filial')),
                ('time_open', models.TimeField(verbose_name='time open')),
                ('time_close', models.TimeField(verbose_name='time close')),
            ],
        ),
    ]
