# Generated by Django 3.2.8 on 2021-10-12 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_back_end', '0002_worktime'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category_2_depart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.IntegerField(verbose_name='Category of key word')),
                ('depart', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Название отдела',
                'verbose_name_plural': 'Назавания отделов',
            },
        ),
        migrations.AlterModelOptions(
            name='category_managers',
            options={'verbose_name': 'Менеджер', 'verbose_name_plural': 'Менеджеры'},
        ),
        migrations.AlterModelOptions(
            name='code_filial_2_name_filial',
            options={'verbose_name': 'Название филиала', 'verbose_name_plural': 'Назавания филиалов'},
        ),
        migrations.AlterModelOptions(
            name='depart_filial_2_phone_number',
            options={'verbose_name': 'Доб.номер', 'verbose_name_plural': 'Доб.номера'},
        ),
        migrations.AlterModelOptions(
            name='three_categories',
            options={'verbose_name': 'Ключевое слово', 'verbose_name_plural': 'Ключевые слова'},
        ),
        migrations.AlterModelOptions(
            name='worktime',
            options={'verbose_name': 'Время работы', 'verbose_name_plural': 'Время работы'},
        ),
        migrations.AlterField(
            model_name='three_categories',
            name='category',
            field=models.IntegerField(verbose_name='Category of key word'),
        ),
    ]
