# Generated by Django 3.2.8 on 2021-11-02 10:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_back_end', '0002_alter_calltrack_lite_date_time_calling'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calltrack_lite',
            name='date_time_calling',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 2, 15, 41, 35, 363679), verbose_name='время звонка'),
        ),
        migrations.AlterField(
            model_name='calltrack_lite',
            name='result_recognition',
            field=models.CharField(default='', max_length=50, verbose_name='распознование'),
        ),
    ]
