# Generated by Django 3.2.8 on 2021-10-12 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_back_end', '0003_auto_20211012_0933'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category_2_depart',
        ),
        migrations.AlterField(
            model_name='code_filial_2_name_filial',
            name='name',
            field=models.CharField(max_length=50, verbose_name='name of city filial'),
        ),
        migrations.AlterField(
            model_name='three_categories',
            name='category',
            field=models.CharField(max_length=50, verbose_name='Category of key word (depart or category)'),
        ),
    ]
