# Generated by Django 3.2.8 on 2021-11-02 10:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_back_end', '0003_auto_20211102_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calltrack_lite',
            name='date_time_calling',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 2, 15, 42, 3, 853911), verbose_name='время звонка'),
        ),
    ]
