# Generated by Django 3.2.8 on 2021-10-12 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_back_end', '0004_auto_20211012_0942'),
    ]

    operations = [
        migrations.CreateModel(
            name='Repeat_hallo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_repeat', models.FloatField(verbose_name='время в секундах после фразы клиента')),
                ('times_repeat', models.IntegerField(verbose_name='количестово повторов')),
                ('phrase_repeat', models.CharField(max_length=50, verbose_name='фраза для повтора')),
            ],
            options={
                'verbose_name': 'Фраза: я вас слушаю',
                'verbose_name_plural': 'Фразы: я вас слушаю',
            },
        ),
        migrations.AlterModelOptions(
            name='depart_filial_2_phone_number',
            options={'verbose_name': 'Доб.номер отдела', 'verbose_name_plural': 'Доб.номера отделов'},
        ),
        migrations.AlterField(
            model_name='category_managers',
            name='name_man',
            field=models.CharField(max_length=100, verbose_name='имя менеджера'),
        ),
        migrations.AlterField(
            model_name='category_managers',
            name='phone_number',
            field=models.CharField(max_length=12, verbose_name='доб. номер'),
        ),
        migrations.AlterField(
            model_name='category_managers',
            name='text',
            field=models.CharField(max_length=50, verbose_name='ключ. слово'),
        ),
        migrations.AlterField(
            model_name='code_filial_2_name_filial',
            name='code_filial',
            field=models.IntegerField(verbose_name='код города филиала'),
        ),
        migrations.AlterField(
            model_name='code_filial_2_name_filial',
            name='name',
            field=models.CharField(max_length=50, verbose_name='название филиала'),
        ),
        migrations.AlterField(
            model_name='depart_filial_2_phone_number',
            name='depart',
            field=models.CharField(max_length=50, verbose_name='отдел'),
        ),
        migrations.AlterField(
            model_name='depart_filial_2_phone_number',
            name='filial',
            field=models.CharField(max_length=50, verbose_name='город филиала'),
        ),
        migrations.AlterField(
            model_name='depart_filial_2_phone_number',
            name='info',
            field=models.CharField(max_length=50, verbose_name='инфо'),
        ),
        migrations.AlterField(
            model_name='depart_filial_2_phone_number',
            name='phone_number',
            field=models.IntegerField(verbose_name='доб. номер'),
        ),
        migrations.AlterField(
            model_name='three_categories',
            name='category',
            field=models.CharField(max_length=50, verbose_name='категория ключ. слово (отдел или категория)'),
        ),
        migrations.AlterField(
            model_name='three_categories',
            name='text',
            field=models.CharField(max_length=50, verbose_name='ключ. слово'),
        ),
        migrations.AlterField(
            model_name='worktime',
            name='filial',
            field=models.CharField(max_length=50, verbose_name='филиал'),
        ),
        migrations.AlterField(
            model_name='worktime',
            name='time_close',
            field=models.TimeField(verbose_name='Конец рабочего дня'),
        ),
        migrations.AlterField(
            model_name='worktime',
            name='time_open',
            field=models.TimeField(verbose_name='Начало рабочего дня'),
        ),
    ]
