# Generated by Django 3.2.8 on 2021-10-13 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_back_end', '0005_auto_20211012_1633'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category_2_name_category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.IntegerField(verbose_name='номер категории')),
                ('name_category', models.CharField(max_length=20, verbose_name='название категории')),
            ],
            options={
                'verbose_name': 'Название категории',
                'verbose_name_plural': 'Названия категорий',
            },
        ),
    ]
