# Generated by Django 3.2.8 on 2021-10-13 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_back_end', '0006_category_2_name_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='three_categories',
            name='category',
            field=models.IntegerField(verbose_name='номер категории'),
        ),
    ]
