# Generated by Django 3.2.8 on 2021-10-13 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot_back_end', '0007_alter_three_categories_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category_2_name_category',
            options={'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='code_filial_2_name_filial',
            options={'verbose_name': 'Филиал', 'verbose_name_plural': 'Филиалы'},
        ),
        migrations.RenameField(
            model_name='code_filial_2_name_filial',
            old_name='name',
            new_name='filial',
        ),
    ]
