# Generated by Django 3.2.8 on 2021-10-15 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_back_end', '0008_auto_20211013_1408'),
    ]

    operations = [
        migrations.CreateModel(
            name='Regions_name_and_code',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_region', models.IntegerField(verbose_name='код региона')),
                ('name_region', models.CharField(max_length=100, verbose_name='название региона')),
            ],
            options={
                'verbose_name': 'Регион',
                'verbose_name_plural': 'Регионы',
            },
        ),
    ]
