# Generated by Django 3.2.8 on 2021-10-15 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_back_end', '0009_regions_name_and_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Relationship_code_region_and_filial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_region', models.IntegerField(verbose_name='код региона')),
                ('code_filial', models.IntegerField(verbose_name='код филиала')),
            ],
            options={
                'verbose_name': 'Регион филиал',
                'verbose_name_plural': 'Регионы филиалов',
            },
        ),
    ]
