# Generated by Django 3.2.8 on 2021-11-10 08:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_back_end', '0010_auto_20211109_1007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calltrack_lite',
            name='date_time_calling',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 10, 13, 34, 41, 781716), verbose_name='время звонка'),
        ),
    ]
