# Generated by Django 3.2.8 on 2021-10-22 05:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_back_end', '0011_auto_20211015_1537'),
    ]

    operations = [
        migrations.CreateModel(
            name='calltrack_lite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_rec', models.CharField(max_length=14, verbose_name='ID из астериск')),
                ('text', models.TextField(default='', verbose_name='фраза клиента')),
                ('text_lemm', models.TextField(default='', verbose_name='нормализированная фраза')),
                ('date_time_calling', models.DateTimeField(default=datetime.datetime(2021, 10, 22, 10, 56, 17, 958383), verbose_name='время звонка')),
                ('innumber', models.CharField(max_length=11, verbose_name='номер тел.')),
                ('region', models.IntegerField(verbose_name='код региона')),
                ('dial_route', models.IntegerField(verbose_name='доб. номер')),
                ('key_words', models.CharField(max_length=150, verbose_name='кл. слова')),
            ],
        ),
        migrations.AlterField(
            model_name='depart_filial_2_phone_number',
            name='filial',
            field=models.CharField(max_length=50, verbose_name='филиал'),
        ),
    ]
