# Generated by Django 3.2.8 on 2021-11-02 04:24

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot_back_end', '0013_auto_20211101_1646'),
    ]

    operations = [
        migrations.AddField(
            model_name='departs',
            name='filial',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='bot_back_end.code_filial_2_name_filial', verbose_name='Филиал'),
        ),
        migrations.AlterField(
            model_name='calltrack_lite',
            name='date_time_calling',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 2, 9, 24, 34, 82205), verbose_name='время звонка'),
        ),
        migrations.AlterField(
            model_name='departs',
            name='depart_name',
            field=models.CharField(max_length=150, verbose_name='название отдела'),
        ),
    ]
