# Generated by Django 3.2.8 on 2021-11-02 04:25

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot_back_end', '0014_auto_20211102_0924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calltrack_lite',
            name='date_time_calling',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 2, 9, 25, 11, 216614), verbose_name='время звонка'),
        ),
        migrations.AlterField(
            model_name='departs',
            name='filial',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot_back_end.code_filial_2_name_filial', verbose_name='Филиал'),
        ),
    ]
