# Generated by Django 3.2.8 on 2021-11-02 04:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_back_end', '0015_auto_20211102_0925'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='departs',
            name='filial',
        ),
        migrations.AlterField(
            model_name='calltrack_lite',
            name='date_time_calling',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 2, 9, 26, 4, 176791), verbose_name='время звонка'),
        ),
    ]
